name: CI
on:
  - pull_request
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dokku-version: 
          - master
          - v0.19.0
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.x
      - name: Setup tests
        run: DOKKU_VERSION=${{ matrix.dokku-version }} make setup
      - name: Increase vm.max_map_count
        run: sudo sysctl -w vm.max_map_count=262144
      - name: Verify README.md
        run: |
          make generate
          if ! git diff --quiet README.md; then
            echo "Please run `make generate`"
            git status --short
            git --no-pager diff README.md
            exit 1
          fi
      - name: Run tests
        run: make test
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: tmp/test-results
          path: test-results
